services:
  app:
    build: .
    command: sh -c "python /code/manage.py db_readiness && python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=db-localdev
      - DB_USER=localdevuser
      - DB_PASS=localdevpassword
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - db-localdev-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db-localdev
      - POSTGRES_USER=localdevuser
      - POSTGRES_PASSWORD=localdevpassword
    
volumes:
  db-localdev-data:
    